; Sound Effects for song Green, version 2.0, generated by Arkos Tracker 2.

Green_SoundEffects
Green_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
Green_SoundEffectsDisarkPointerRegionStart0
	dw Green_SoundEffects_Sound1	; Sound effect 1.
	dw Green_SoundEffects_Sound2	; Sound effect 2.
	dw Green_SoundEffects_Sound3	; Sound effect 3.
	dw Green_SoundEffects_Sound4	; Sound effect 4.
	dw Green_SoundEffects_Sound5	; Sound effect 5.
Green_SoundEffectsDisarkPointerRegionEnd0

Green_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
Green_SoundEffects_Sound1
	db 0	; Speed

Green_SoundEffects_Sound1_Loop	db 57	; Soft only. Volume: 14.
	dw 96	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 96	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 128	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 128	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 256	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 256	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 128	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 128	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 128	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 128	; Software period.

	db 4	; End of the sound effect.

; Sound effect 2.
Green_SoundEffects_Sound2
	db 0	; Speed

	db 57	; Soft only. Volume: 14.
	dw 96	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 96	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 112	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 112	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 128	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 128	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 128	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 128	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 128	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 128	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 96	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 96	; Software period.

Green_SoundEffects_Sound2_Loop	db 1	; Soft only. Volume: 0.
	dw 96	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 96	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 128	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 128	; Software period.

	db 4	; End of the sound effect.

; Sound effect 3.
Green_SoundEffects_Sound3
	db 0	; Speed

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 128	; Software period.

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 128	; Software period.

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 128	; Software period.

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 128	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 128	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 96	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 96	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 256	; Software period.

Green_SoundEffects_Sound3_Loop	db 49	; Soft only. Volume: 12.
	dw 256	; Software period.

	db 4	; End of the sound effect.

; Sound effect 4.
Green_SoundEffects_Sound4
	db 0	; Speed

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 256	; Software period.

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 256	; Software period.

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 512	; Software period.

	db 185	; Soft only. Volume: 14.
	db 1	; Noise: 1.
	dw 512	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 640	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 640	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 608	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 608	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 768	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 768	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 1024	; Software period.

Green_SoundEffects_Sound4_Loop	db 33	; Soft only. Volume: 8.
	dw 1024	; Software period.

	db 4	; End of the sound effect.

; Sound effect 5.
Green_SoundEffects_Sound5
	db 0	; Speed

	db 57	; Soft only. Volume: 14.
	dw 512	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 512	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 608	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 608	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 800	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 800	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 768	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 1024	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 1280	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 1536	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 2048	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 2048	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 2048	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 2048	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 2048	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 2048	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 2048	; Software period.

Green_SoundEffects_Sound5_Loop	db 25	; Soft only. Volume: 6.
	dw 2048	; Software period.

	db 4	; End of the sound effect.

Green_SoundEffectsDisarkByteRegionEnd1
