name: MS-DOS
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install DJGPP
      run: |
        # Download DJGPP
        Invoke-WebRequest -Uri https://github.com/pdpdds/kingsvalley/releases/download/1.0/djgpp.zip -OutFile djgpp.zip        
        # Extract DJGPP
        powershell -Command "Expand-Archive -Path djgpp.zip -DestinationPath .\game\djgpp"    
    - name: Build with DJGPP
      run: |
        # Go to DJGPP folder
        echo "PATH=$(echo ${{ github.workspace }}/game/djgpp/djgpp/i586-pc-msdosdjgpp/bin:${{ github.workspace }}/game/djgpp/djgpp/bin:${{ github.workspace }}/game/djgpp/djgpp/nasm:${{ github.workspace }}/game/djgpp/tools:$PATH)" >> $GITHUB_AA
        SET $GITHUB_AA
        echo "GCC_EXEC=$(echo ${{ github.workspace }}/game/djgpp/djgpp/lib/gcc/)" >> $GITHUB_GCC_EXEC
        SET $GITHUB_GCC_EXEC
        SET DJGPP_GCC=gcc
        echo "DJDIR=$(echo ${{ github.workspace }}/game/djgpp/djgpp/i586-pc-msdosdjgpp)" >> $GITHUB_DJDIR
        SET $GITHUB_DJDIR
        cd game
        cd djgpp
        # Run djgpp.bat using cmd.exe
        # cmd.exe /C djgpp.bat
        # Run make command
        make
