name: MS-DOS
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install DJGPP
      run: |
        # Download DJGPP
        Invoke-WebRequest -Uri https://github.com/pdpdds/kingsvalley/releases/download/1.0/djgpp.zip -OutFile djgpp.zip        
        # Extract DJGPP
        powershell -Command "Expand-Archive -Path djgpp.zip -DestinationPath .\game\djgpp"    
    - name: Build with DJGPP
      run: |
        # Go to DJGPP folder
        SET $GITHUB_WORKSPACE\game\djgpp\djgpp\bin;$GITHUB_WORKSPACE\game\djgpp\djgpp\i586-pc-msdosdjgpp;$GITHUB_WORKSPACE\game\djgpp\djgpp\bin;$GITHUB_WORKSPACE\game\djgpp\djgpp\nasm;$GITHUB_WORKSPACE\game\djgpp\djgpp\..\tools;%PATH%
        SET GCC_EXEC_PREFIX=$GITHUB_WORKSPACE\game\djgpp\djgpp\lib\gcc\
        SET DJGPP_GCC=gcc
        SET DJDIR=$GITHUB_WORKSPACE\game\djgpp\djgpp\i586-pc-msdosdjgpp
        cd game
        cd djgpp
        # Run djgpp.bat using cmd.exe
        # cmd.exe /C djgpp.bat
        # Run make command
        make
